/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Thrift.GameCall
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class PlayerInfo : TBase
  {
    private double _X;
    private double _Y;
    private double _Z;
    private double _R;
    private List<sbyte> _name;
    private int _Level;
    private int _ActorCode;
    private int _HP;
    private int _MaxHP;
    private int _MP;
    private int _MaxMP;

    public double X
    {
      get
      {
        return _X;
      }
      set
      {
        __isset.X = true;
        this._X = value;
      }
    }

    public double Y
    {
      get
      {
        return _Y;
      }
      set
      {
        __isset.Y = true;
        this._Y = value;
      }
    }

    public double Z
    {
      get
      {
        return _Z;
      }
      set
      {
        __isset.Z = true;
        this._Z = value;
      }
    }

    public double R
    {
      get
      {
        return _R;
      }
      set
      {
        __isset.R = true;
        this._R = value;
      }
    }

    public List<sbyte> Name
    {
      get
      {
        return _name;
      }
      set
      {
        __isset.name = true;
        this._name = value;
      }
    }

    public int Level
    {
      get
      {
        return _Level;
      }
      set
      {
        __isset.Level = true;
        this._Level = value;
      }
    }

    public int ActorCode
    {
      get
      {
        return _ActorCode;
      }
      set
      {
        __isset.ActorCode = true;
        this._ActorCode = value;
      }
    }

    public int HP
    {
      get
      {
        return _HP;
      }
      set
      {
        __isset.HP = true;
        this._HP = value;
      }
    }

    public int MaxHP
    {
      get
      {
        return _MaxHP;
      }
      set
      {
        __isset.MaxHP = true;
        this._MaxHP = value;
      }
    }

    public int MP
    {
      get
      {
        return _MP;
      }
      set
      {
        __isset.MP = true;
        this._MP = value;
      }
    }

    public int MaxMP
    {
      get
      {
        return _MaxMP;
      }
      set
      {
        __isset.MaxMP = true;
        this._MaxMP = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool X;
      public bool Y;
      public bool Z;
      public bool R;
      public bool name;
      public bool Level;
      public bool ActorCode;
      public bool HP;
      public bool MaxHP;
      public bool MP;
      public bool MaxMP;
    }

    public PlayerInfo() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Double) {
              X = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Double) {
              Y = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Double) {
              Z = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.Double) {
              R = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.List) {
              {
                Name = new List<sbyte>();
                TList _list0 = iprot.ReadListBegin();
                for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                {
                  sbyte _elem2 = 0;
                  _elem2 = iprot.ReadByte();
                  Name.Add(_elem2);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.I32) {
              Level = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.I32) {
              ActorCode = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 8:
            if (field.Type == TType.I32) {
              HP = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 9:
            if (field.Type == TType.I32) {
              MaxHP = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 10:
            if (field.Type == TType.I32) {
              MP = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 11:
            if (field.Type == TType.I32) {
              MaxMP = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("PlayerInfo");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.X) {
        field.Name = "X";
        field.Type = TType.Double;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(X);
        oprot.WriteFieldEnd();
      }
      if (__isset.Y) {
        field.Name = "Y";
        field.Type = TType.Double;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(Y);
        oprot.WriteFieldEnd();
      }
      if (__isset.Z) {
        field.Name = "Z";
        field.Type = TType.Double;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(Z);
        oprot.WriteFieldEnd();
      }
      if (__isset.R) {
        field.Name = "R";
        field.Type = TType.Double;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(R);
        oprot.WriteFieldEnd();
      }
      if (Name != null && __isset.name) {
        field.Name = "name";
        field.Type = TType.List;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Byte, Name.Count));
          foreach (sbyte _iter3 in Name)
          {
            oprot.WriteByte(_iter3);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (__isset.Level) {
        field.Name = "Level";
        field.Type = TType.I32;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Level);
        oprot.WriteFieldEnd();
      }
      if (__isset.ActorCode) {
        field.Name = "ActorCode";
        field.Type = TType.I32;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ActorCode);
        oprot.WriteFieldEnd();
      }
      if (__isset.HP) {
        field.Name = "HP";
        field.Type = TType.I32;
        field.ID = 8;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(HP);
        oprot.WriteFieldEnd();
      }
      if (__isset.MaxHP) {
        field.Name = "MaxHP";
        field.Type = TType.I32;
        field.ID = 9;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(MaxHP);
        oprot.WriteFieldEnd();
      }
      if (__isset.MP) {
        field.Name = "MP";
        field.Type = TType.I32;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(MP);
        oprot.WriteFieldEnd();
      }
      if (__isset.MaxMP) {
        field.Name = "MaxMP";
        field.Type = TType.I32;
        field.ID = 11;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(MaxMP);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("PlayerInfo(");
      sb.Append("X: ");
      sb.Append(X);
      sb.Append(",Y: ");
      sb.Append(Y);
      sb.Append(",Z: ");
      sb.Append(Z);
      sb.Append(",R: ");
      sb.Append(R);
      sb.Append(",Name: ");
      sb.Append(Name);
      sb.Append(",Level: ");
      sb.Append(Level);
      sb.Append(",ActorCode: ");
      sb.Append(ActorCode);
      sb.Append(",HP: ");
      sb.Append(HP);
      sb.Append(",MaxHP: ");
      sb.Append(MaxHP);
      sb.Append(",MP: ");
      sb.Append(MP);
      sb.Append(",MaxMP: ");
      sb.Append(MaxMP);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
